Repository surfstudio/StackOv, pull requests merged in 2021-01, with the labels that each got.

#30 Update and rename build-and-check.yml to dev-pull-request-checker.yml
  .github/workflows/build-and-check.yml
  .github/workflows/dev-pull-request-checker.yml
  .slather.yml
  Common/Package.swift
  Network/Package.swift
  Network/Sources/Network/Extensions/DataTaskPublisher.swift
  Network/Sources/Network/Extensions/HTTPURLResponse.swift
  Network/Sources/Network/HTTPStatusCode.swift
  Network/Sources/Network/MethodWrapping.swift
  Network/Sources/Network/Network.swift
  Network/Sources/Network/Request.swift
  Palette/Package.swift
  README.md
  Services/StackexchangeNetworkService/Sources/StackexchangeNetworkService/Requests/LoadAnswerRequests.swift
  Services/StackexchangeNetworkService/Sources/StackexchangeNetworkService/Requests/LoadAnswersRequests.swift
  Services/StackexchangeNetworkService/Sources/StackexchangeNetworkService/Requests/LoadQuestionRequests.swift
  Services/StackexchangeNetworkService/Sources/StackexchangeNetworkService/Requests/LoadQuestionsRequests.swift
  Services/StackexchangeNetworkService/Sources/StackexchangeNetworkService/Requests/SearchQuestionsRequests.swift
  Shared/StackOvApp.swift
  StackOv.xcodeproj/project.pbxproj
  StackOv.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  StackOv.xcodeproj/xcshareddata/xcschemes/StackOv (iOS).xcscheme
Labels: Service task

#31 Update for the github actions workflow
  .github/workflows/change-checker.yml
Labels: Service task

#36 Feature/32 post cell refactoring
  .github/workflows/change-checker.yml
  Components/Sources/Components/TagButton.swift
  Flows/HomeFlow/Sources/HomeFlow/HomeFlow.swift
  Flows/HomeFlow/Sources/HomeFlow/PageView/PageView.swift
  Flows/HomeFlow/Sources/HomeFlow/PostItemView/Models/PostItemViewModel.swift
  Flows/HomeFlow/Sources/HomeFlow/PostItemView/PostItemInfoView.swift
  Flows/HomeFlow/Sources/HomeFlow/PostItemView/PostItemView.swift
Labels: Any device, enhancement

#40 Hotfix/custom file header
  AppScript/Sources/AppScript/Services.swift
  AppScript/Sources/AppScript/Stores.swift
  AppScript/Sources/AppScript/Wrappers.swift
  Common/Sources/Common/Extensions/EdgeInsets+Extensions.swift
  Common/Sources/Common/Extensions/String+Extensions.swift
  Common/Sources/Common/Extensions/UIUserInterfaceIdiom.swift
  Common/Sources/Common/Helpers/Lazy.swift
  Components/Sources/Components/BadgeView.swift
  Components/Sources/Components/EllipsisButton.swift
  Components/Sources/Components/FilterButton.swift
  Components/Sources/Components/PageButton/PageButton.swift
  Components/Sources/Components/PageButton/PageModel.swift
  Components/Sources/Components/PageDevMock.swift
  Components/Sources/Components/TagButton.swift
  Components/Sources/Components/TagFilter.swift
  Components/Sources/Components/TagsCollection.swift
  DataTransferObjects/Sources/DataTransferObjects/AnswerEntry.swift
  DataTransferObjects/Sources/DataTransferObjects/PostsEntry.swift
  DataTransferObjects/Sources/DataTransferObjects/QuestionEntry.swift
  DataTransferObjects/Sources/DataTransferObjects/UserEntry.swift
  Flows/FavoriteFlow/Sources/FavoriteFlow/FavoriteFlow.swift
  Flows/HomeFlow/Sources/HomeFlow/HomeFlow.swift
  Flows/HomeFlow/Sources/HomeFlow/PageView/PageView.swift
  Flows/HomeFlow/Sources/HomeFlow/PagesView/PagesView.swift
  Flows/HomeFlow/Sources/HomeFlow/QuestionItemView/Models/QuestionItemViewModel.swift
  Flows/HomeFlow/Sources/HomeFlow/QuestionItemView/QuestionItemInfoView.swift
  Flows/HomeFlow/Sources/HomeFlow/QuestionItemView/QuestionItemView.swift
  Flows/MessagesFlow/Sources/MessagesFlow/MessagesFlow.swift
  Flows/TagsFlow/Sources/TagsFlow/TagsFlow.swift
  Flows/UsersFlow/Sources/UsersFlow/UsersFlow.swift
  Network/Sources/Network/Extensions/DataTaskPublisher.swift
  Network/Sources/Network/HTTPWrappers.swift
  Network/Sources/Network/MethodWrapping.swift
  Network/Sources/Network/Request.swift
  Palette/Sources/Palette/RecursivePalette.swift
  Palette/Sources/Palette/UIColor+Extensions.swift
  Services/StackexchangeNetworkService/Sources/StackexchangeNetworkService/Requests/LoadAnswerRequests.swift
  Services/StackexchangeNetworkService/Sources/StackexchangeNetworkService/Requests/LoadAnswersRequests.swift
  Services/StackexchangeNetworkService/Sources/StackexchangeNetworkService/Requests/LoadQuestionRequests.swift
  Services/StackexchangeNetworkService/Sources/StackexchangeNetworkService/Requests/LoadQuestionsRequests.swift
  Services/StackexchangeNetworkService/Sources/StackexchangeNetworkService/Requests/SearchQuestionsRequests.swift
  Services/StackexchangeNetworkService/Sources/StackexchangeNetworkService/StackexchangeNetworkService.swift
  Shared/ContentView.swift
  Shared/Persistence.swift
  Shared/SidebarView/SidebarButton.swift
  Shared/SidebarView/SidebarView.swift
  Shared/SidebarView/UserView.swift
  Shared/StackOvApp.swift
  StackOv.xcodeproj/project.pbxproj
  StackOv.xcodeproj/project.xcworkspace/xcshareddata/IDETemplateMacros.plist
  StackOv.xcodeproj/xcshareddata/IDETemplateMacros.plist
  StackOv.xcodeproj/xcshareddata/xcschemes/StackOv (iOS).xcscheme
  Stores/PageStore/Sources/PageStore/Models/QuestionItemModel.swift
  Stores/PageStore/Sources/PageStore/PageDataManager/PageDataManager.swift
  Stores/PageStore/Sources/PageStore/PageDataManager/PageDataManagerProtocol.swift
  Stores/PageStore/Sources/PageStore/PageStore.swift
  Tests iOS/Info.plist
  Tests iOS/Tests_iOS.swift
  iOS/PhoneContentView.swift
  iPadOS/PadContentView.swift
Labels: Service task

#39 Feature/35 filter view layout (for checking)
  Components/Sources/Components/CheckmarkView.swift
  Flows/HomeFlow/Sources/HomeFlow/FilterView/FilterView.swift
  Flows/HomeFlow/Sources/HomeFlow/FilterView/Models/FilterOption.swift
  Flows/HomeFlow/Sources/HomeFlow/FilterView/Models/SortOption.swift
  Flows/HomeFlow/Sources/HomeFlow/FilterView/Rows/FilterOptionRow.swift
  Flows/HomeFlow/Sources/HomeFlow/FilterView/Rows/SortOptionRow.swift
  Flows/HomeFlow/Sources/HomeFlow/HomeFlow.swift
  Palette/Sources/Palette/Palette.xcassets/Bluishblack.colorset/Contents.json
  Palette/Sources/Palette/Palette.xcassets/DullGray.colorset/Contents.json
  Palette/Sources/Palette/Palette.xcassets/Gainsboro.colorset/Contents.json
  Palette/Sources/Palette/Palette.xcassets/Grayblue.colorset/Contents.json
  Palette/Sources/Palette/Palette.xcassets/Main.colorset/Contents.json
  Palette/Sources/Palette/Palette.xcassets/Telegrey.colorset/Contents.json
Labels: Any device, Layout, enhancement
