Repository surfstudio/StackOv, pull requests merged in 2021-04, with the labels that each got.

#75 Notifications snacks + error handling
  AppScript/Package.swift
  AppScript/Sources/AppScript/Stores.swift
  Common/Package.swift
  Common/Sources/Common/GlobalBanner/GlobalBanner.swift
  Common/Sources/Common/NotificationBannerModel.swift
  Components/Package.swift
  Components/Sources/Components/NotificationBanner/NotificationBannerView.swift
  Errors/.gitignore
  Errors/Package.swift
  Errors/README.md
  Errors/Sources/Errors/DisplaybleError.swift
  Errors/Sources/Errors/HTTPError.swift
  Errors/Sources/Errors/HTTPStatusCode.swift
  Flows/MainFlow/Package.swift
  Flows/MainFlow/Sources/MainFlow/GlobalBannerModifier.swift
  Flows/MainFlow/Sources/MainFlow/MainFlow.swift
  Network/Sources/Network/Extensions/HTTPURLResponse.swift
  Palette/Sources/Palette/Palette.swift
  Palette/Sources/Palette/Palette.xcassets/Black.colorset/Contents.json
  Palette/Sources/Palette/Palette.xcassets/Gray.colorset/Contents.json
  Palette/Sources/Palette/Palette.xcassets/Red.colorset/Contents.json
  Palette/Sources/Palette/Palette.xcassets/SteelGray300.colorset/Contents.json
  StackOv.xcodeproj/project.pbxproj
  StackOv.xcodeproj/xcshareddata/xcschemes/StackOv (iOS).xcscheme
  Stores/GlobalBannerStore/.swiftpm/xcode/xcshareddata/xcschemes/GlobalBannerStore.xcscheme
  Stores/GlobalBannerStore/Package.swift
  Stores/GlobalBannerStore/README.md
  Stores/GlobalBannerStore/Sources/GlobalBannerStore/GlobalBannerStore.swift
  Stores/GlobalBannerStore/Tests/GlobalBannerStoreTests/GlobalBannerStoreTests.swift
  Stores/PageStore/Package.swift
  Stores/PageStore/Sources/PageStore/PageStore.swift
Labels: High, feature

#76 Feature/55 markdown logic refactoring
  Markdown/Sources/Markdown/Unit/SnippetContainer.swift
  Markdown/Sources/Markdown/Unit/Unit.swift
  Markdown/Tests/MarkdownTests/MarkdownTests.swift
Labels: Service task, feature

#78 Feature/71 Support different layouts
  AppScript/Package.swift
  AppScript/Sources/AppScript/Stores.swift
  Components/Package.swift
  Components/Sources/Components/SidebarLeftButton.swift
  Flows/HomeFlow/Sources/HomeFlow/PageView/PageView.swift
  Flows/HomeFlow/Sources/HomeFlow/PostView/PostView.swift
  Flows/MainFlow/Sources/MainFlow/PadContentView.swift
  Flows/MainFlow/Sources/MainFlow/Sidebar/SidebarContentView.swift
  Flows/MainFlow/Sources/MainFlow/Sidebar/SidebarView.swift
  StackOv.xcodeproj/project.pbxproj
  StackOv.xcodeproj/xcshareddata/xcschemes/StackOv (iOS).xcscheme
  Stores/GlobalBannerStore/Package.swift
  Stores/GlobalBannerStore/Sources/GlobalBannerStore/GlobalBannerStore.swift
  Stores/SidebarStore/.swiftpm/xcode/xcshareddata/xcschemes/SidebarStore.xcscheme
  Stores/SidebarStore/Package.swift
  Stores/SidebarStore/README.md
  Stores/SidebarStore/Sources/SidebarStore/SidebarStore.swift
  Stores/SidebarStore/Tests/SidebarStoreTests/SidebarStoreTests.swift
Labels: Any device, WIP, feature

#80 Feature/72 Short version for sidebar view
  Common/Sources/Common/Constants/SidebarConstants.swift
  Flows/HomeFlow/Sources/HomeFlow/PageView/PageView.swift
  Flows/MainFlow/Package.swift
  Flows/MainFlow/Sources/MainFlow/Sidebar/Compact/CompactSidebarButton.swift
  Flows/MainFlow/Sources/MainFlow/Sidebar/Compact/CompactSidebarView.swift
  Flows/MainFlow/Sources/MainFlow/Sidebar/Compact/CompactUserView.swift
  Flows/MainFlow/Sources/MainFlow/Sidebar/Regular/RegularSidebarButton.swift
  Flows/MainFlow/Sources/MainFlow/Sidebar/Regular/RegularSidebarView.swift
  Flows/MainFlow/Sources/MainFlow/Sidebar/Regular/RegularUserView.swift
  Flows/MainFlow/Sources/MainFlow/Sidebar/SidebarView.swift
Labels: WIP, feature, iPad

#79 Feature/38 Post tags functionality
  Components/Sources/Components/TagButton.swift
  Flows/FavoriteFlow/Sources/FavoriteFlow/PostItemView/PostItemView.swift
  Flows/HomeFlow/Sources/HomeFlow/FilterView/FilterView.swift
  Flows/HomeFlow/Sources/HomeFlow/PostItemView/PostItemView.swift
Labels: feature

#84 Feature/81 Thread Flow step1
  Common/Sources/Common/Models/QuestionModel.swift
  Common/Sources/Common/PostActivity.swift
  Components/Sources/Components/ThreadItemView/ThreadItemView.swift
  DataTransferObjects/Sources/DataTransferObjects/QuestionEntry.swift
  Flows/ThreadFlow/Sources/ThreadFlow/QuestionView.swift
  Flows/ThreadFlow/Sources/ThreadFlow/QuestionView/PadQuestionView.swift
  Flows/ThreadFlow/Sources/ThreadFlow/QuestionView/PhoneQuestionView.swift
  Flows/ThreadFlow/Sources/ThreadFlow/QuestionView/QuestionView.swift
  Flows/ThreadFlow/Sources/ThreadFlow/RetingView/RetingView.swift
  Flows/ThreadFlow/Sources/ThreadFlow/ThreadFlow.swift
  Network/Sources/Network/Request.swift
  Services/StackexchangeNetworkService/Sources/StackexchangeNetworkService/Extensions/Request+Extension.swift
  Services/StackexchangeNetworkService/Sources/StackexchangeNetworkService/Requests/LoadAnswerRequests.swift
  Services/StackexchangeNetworkService/Sources/StackexchangeNetworkService/Requests/LoadAnswersRequests.swift
  Services/StackexchangeNetworkService/Sources/StackexchangeNetworkService/Requests/LoadQuestionRequests.swift
  Services/StackexchangeNetworkService/Sources/StackexchangeNetworkService/Requests/LoadQuestionsRequests.swift
  Services/StackexchangeNetworkService/Sources/StackexchangeNetworkService/Requests/SearchQuestionsRequests.swift
  Services/StackexchangeNetworkService/Sources/StackexchangeNetworkService/StackexchangeNetworkService.swift
Labels: Any device, feature

#85 Feature/83 update thread flow step2
  AppScript/Sources/AppScript/Services.swift
  AppScript/Sources/AppScript/Stores.swift
  Common/Sources/Common/Models/AnswerModel.swift
  Common/Sources/Common/Models/PostModel.swift
  Common/Sources/Common/Models/QuestionModel.swift
  Components/Sources/Components/MarkdownPostView/Blocks/CodeBlockView.swift
  Components/Sources/Components/MarkdownPostView/Blocks/GlobalBlockView.swift
  Components/Sources/Components/MarkdownPostView/Blocks/SnippetBlockView.swift
  Components/Sources/Components/MarkdownPostView/MarkdownPostView.swift
  Flows/ThreadFlow/Sources/ThreadFlow/PostView/PostView.swift
  Flows/ThreadFlow/Sources/ThreadFlow/QuestionView/PadQuestionView.swift
  Flows/ThreadFlow/Sources/ThreadFlow/QuestionView/PhoneQuestionView.swift
  Flows/ThreadFlow/Sources/ThreadFlow/ThreadFlow.swift
  Markdown/Sources/Markdown/Unit/Unit.swift
  Markdown/Sources/Markdown/Unit/UnitData.swift
  Stores/ThreadStore/Sources/ThreadStore/ThreadDataManager/ThreadDataManager.swift
  Stores/ThreadStore/Sources/ThreadStore/ThreadDataManager/ThreadDataManagerProtocol.swift
  Stores/ThreadStore/Sources/ThreadStore/ThreadStore.swift
Labels: Any device, WIP, feature

#92 Page's item style upgrade
  Common/Package.swift
  Common/Sources/Common/Extensions/View+Extensions.swift
  Common/Sources/Common/Models/QuestionModel.swift
  Components/Sources/Components/TagsCollection.swift
  Components/Sources/Components/ThreadItemView/ThreadItemNavigationLinkStyle.swift
  Components/Sources/Components/ThreadItemView/ThreadItemView.swift
  Flows/HomeFlow/Sources/HomeFlow/PageView/PageView.swift
  Palette/Sources/Palette/Palette.swift
  Palette/Sources/Palette/Palette.xcassets/DarkShadow.colorset/Contents.json
  Palette/Sources/Palette/RecursivePalette.swift
  Services/StackexchangeNetworkService/Sources/StackexchangeNetworkService/Requests/LoadQuestionsRequests.swift
  StackOv.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: Any device, feature

#93 Feature/86 Update ThreadFlow (Step 3)
  AppScript/Package.swift
  AppScript/Sources/AppScript/Stores.swift
  Common/Sources/Common/Extensions/String+Extensions.swift
  Common/Sources/Common/Models/AnswerModel.swift
  Common/Sources/Common/Models/CommentModel.swift
  Common/Sources/Common/Models/PostModel.swift
  Common/Sources/Common/Models/QuestionModel.swift
  Common/Sources/Common/Models/ShallowUserModel.swift
  Common/Sources/Common/Models/UserModel.swift
  Components/Sources/Components/PersonInfoView.swift
  Components/Sources/Components/TagButton/TagButton.swift
  Components/Sources/Components/TagsCollection.swift
  Components/Sources/Components/ThreadItemView/ThreadItemNavigationLinkStyle.swift
  Components/Sources/Components/ThreadItemView/ThreadItemView.swift
  DataTransferObjects/Sources/DataTransferObjects/AnswerEntry.swift
  DataTransferObjects/Sources/DataTransferObjects/CommentEntry.swift
  DataTransferObjects/Sources/DataTransferObjects/QuestionEntry.swift
  DataTransferObjects/Sources/DataTransferObjects/ShallowUserEntry.swift
  Flows/ThreadFlow/Sources/ThreadFlow/AnswerView/AnswerView.swift
  Flows/ThreadFlow/Sources/ThreadFlow/AnswerView/PadAnswerView.swift
  Flows/ThreadFlow/Sources/ThreadFlow/AnswerView/PhoneAnswerView.swift
  Flows/ThreadFlow/Sources/ThreadFlow/CommentsView/CommentsView.swift
  Flows/ThreadFlow/Sources/ThreadFlow/PostView/PostView.swift
  Flows/ThreadFlow/Sources/ThreadFlow/QuestionView/PadQuestionView.swift
  Flows/ThreadFlow/Sources/ThreadFlow/QuestionView/PhoneQuestionView.swift
  Flows/ThreadFlow/Sources/ThreadFlow/QuestionView/QuestionView.swift
  Flows/ThreadFlow/Sources/ThreadFlow/RetingView/RetingView.swift
  Flows/ThreadFlow/Sources/ThreadFlow/ThreadFlow.swift
  Services/StackexchangeNetworkService/Sources/StackexchangeNetworkService/StackexchangeNetworkService.swift
  StackOv.xcodeproj/project.pbxproj
  StackOv.xcodeproj/xcshareddata/xcschemes/StackOv (iOS).xcscheme
  Stores/CommentsStore/Package.swift
  Stores/CommentsStore/README.md
  Stores/CommentsStore/Sources/CommentsStore/CommentsStore.swift
  Stores/CommentsStore/Tests/CommentsStoreTests/CommentsStoreTests.swift
Labels: Any device, feature

#95 Network services were upgraded
  Common/Sources/Common/Extensions/DataTaskPublisher+Extensions.swift
  Common/Sources/Common/Extensions/HTTPURLResponse+Extensions.swift
  Common/Sources/Common/Extensions/String+Extensions.swift
  Common/Sources/Common/Extensions/UIUserInterfaceIdiom+Extensions.swift
  DataTransferObjects/Sources/DataTransferObjects/AnswerEntry.swift
  DataTransferObjects/Sources/DataTransferObjects/QuestionEntry.swift
  Errors/Sources/Errors/ServiceError.swift
  Network/.swiftpm/xcode/xcshareddata/xcschemes/Network.xcscheme
  Network/Package.swift
  Network/README.md
  Network/Sources/Network/HTTPWrappers.swift
  Network/Sources/Network/MethodWrapping.swift
  Network/Sources/Network/Request.swift
  Network/Tests/NetworkTests/NetworkTests.swift
  Services/StackexchangeNetworkService/Package.swift
  Services/StackexchangeNetworkService/Sources/StackexchangeNetworkService/Extensions/Request+Extension.swift
  Services/StackexchangeNetworkService/Sources/StackexchangeNetworkService/Requests/LoadAnswerRequests.swift
  Services/StackexchangeNetworkService/Sources/StackexchangeNetworkService/Requests/LoadAnswersRequests.swift
  Services/StackexchangeNetworkService/Sources/StackexchangeNetworkService/Requests/LoadQuestionRequests.swift
  Services/StackexchangeNetworkService/Sources/StackexchangeNetworkService/Requests/LoadQuestionsRequests.swift
  Services/StackexchangeNetworkService/Sources/StackexchangeNetworkService/Requests/SearchQuestionsRequests.swift
  Services/StackexchangeNetworkService/Sources/StackexchangeNetworkService/StackexchangeNetworkService.swift
  StackOv.xcodeproj/project.pbxproj
  Stores/FavoriteStore/Sources/FavoriteStore/FavoriteDataManager/FavoriteDataManager.swift
  Stores/PageStore/Sources/PageStore/PageDataManager/PageDataManager.swift
  Stores/ThreadStore/Sources/ThreadStore/ThreadDataManager/ThreadDataManager.swift
Labels: High, hotfix
