Repository surfstudio/StackOv, pull requests merged in 2021-03, with the labels that each got.

#49 FilterStore of Module for filtering posts on a search page
  AppScript/Package.swift
  AppScript/Sources/AppScript/Stores.swift
  Flows/HomeFlow/Sources/HomeFlow/FilterView/FilterView.swift
  Flows/HomeFlow/Sources/HomeFlow/FilterView/Models/FilterOption.swift
  Flows/HomeFlow/Sources/HomeFlow/FilterView/Models/SortOption.swift
  Flows/HomeFlow/Sources/HomeFlow/FilterView/Rows/FilterOptionRow.swift
  Flows/HomeFlow/Sources/HomeFlow/FilterView/Rows/SortOptionRow.swift
  Flows/HomeFlow/Sources/HomeFlow/HomeFlow.swift
  Flows/HomeFlow/Sources/HomeFlow/PageView/PageView.swift
  StackOv.xcodeproj/project.pbxproj
  StackOv.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  StackOv.xcodeproj/xcshareddata/xcschemes/StackOv (iOS).xcscheme
  Stores/FilterStore/Package.swift
  Stores/FilterStore/README.md
  Stores/FilterStore/Sources/FilterStore/FilterStore.swift
  Stores/FilterStore/Tests/FilterStoreTests/FilterStoreTests.swift
  Stores/FilterStore/Tests/FilterStoreTests/XCTestManifests.swift
  Stores/FilterStore/Tests/LinuxMain.swift
  Stores/PageStore/Package.swift
  Stores/PageStore/Sources/PageStore/PageStore.swift
Labels: feature

#51 Main flow was added
  Common/Sources/Common/Extensions/UIApplication+Extensions.swift
  Common/Sources/Common/Extensions/View+Extensions.swift
  Components/Sources/Components/BadgeView.swift
  Components/Sources/Components/CheckmarkView.swift
  Components/Sources/Components/EllipsisButton.swift
  Components/Sources/Components/FilterButton.swift
  Components/Sources/Components/MarkdownPostView/Blocks/CodeBlockView.swift
  Components/Sources/Components/MarkdownPostView/Blocks/SnippetBlockView.swift
  Components/Sources/Components/MarkdownPostView/MarkdownTextView.swift
  Components/Sources/Components/PageButton/PageButton.swift
  Components/Sources/Components/TagButton.swift
  Components/Sources/Components/TagFilter.swift
  Flows/HomeFlow/Sources/HomeFlow/FilterView/Rows/FilterOptionRow.swift
  Flows/HomeFlow/Sources/HomeFlow/FilterView/Rows/SortOptionRow.swift
  Flows/HomeFlow/Sources/HomeFlow/HomeFlow.swift
  Flows/HomeFlow/Sources/HomeFlow/PageView/PageView.swift
  Flows/HomeFlow/Sources/HomeFlow/PostItemView/PostItemView.swift
  Flows/MainFlow/Package.swift
  Flows/MainFlow/README.md
  Flows/MainFlow/Sources/MainFlow/MainBar/MainBar.swift
  Flows/MainFlow/Sources/MainFlow/MainFlow.swift
  Flows/MainFlow/Sources/MainFlow/PadContentView.swift
  Flows/MainFlow/Sources/MainFlow/PhoneContentView.swift
  Flows/MainFlow/Sources/MainFlow/Sidebar/SidebarButton.swift
  Flows/MainFlow/Sources/MainFlow/Sidebar/SidebarView.swift
  Flows/MainFlow/Sources/MainFlow/Sidebar/UserView.swift
  Icons/Sources/Icons/Icons.swift
  Icons/Sources/Icons/Icons.xcassets/arrow.left.imageset/Contents.json
  Icons/Sources/Icons/Icons.xcassets/bell.fill.imageset/Contents.json
  Icons/Sources/Icons/Icons.xcassets/bell.imageset/Contents.json
  Icons/Sources/Icons/Icons.xcassets/bookmark.fill.imageset/Contents.json
  Icons/Sources/Icons/Icons.xcassets/bookmark.imageset/Contents.json
  Icons/Sources/Icons/Icons.xcassets/checkmark.circle.fill.imageset/Contents.json
  Icons/Sources/Icons/Icons.xcassets/checkmark.imageset/Contents.json
  Icons/Sources/Icons/Icons.xcassets/eye.fill.imageset/Contents.json
  Icons/Sources/Icons/Icons.xcassets/hand.thumbsdown.fill.imageset/Contents.json
  Icons/Sources/Icons/Icons.xcassets/hand.thumbsup.fill.imageset/Contents.json
  Icons/Sources/Icons/Icons.xcassets/magnifyingglass.imageset/Contents.json
  Icons/Sources/Icons/Icons.xcassets/paperclip.imageset/Contents.json
  Icons/Sources/Icons/Icons.xcassets/pencil.imageset/Contents.json
  Icons/Sources/Icons/Icons.xcassets/person.2.fill.imageset/Contents.json
  Icons/Sources/Icons/Icons.xcassets/planet.imageset/Contents.json
  Icons/Sources/Icons/Icons.xcassets/square.and.arrow.up.imageset/Contents.json
  Icons/Sources/Icons/Icons.xcassets/star.fill.imageset/Contents.json
  Icons/Sources/Icons/Icons.xcassets/star.imageset/Contents.json
  Icons/Sources/Icons/Icons.xcassets/star.rounded.fill.imageset/Contents.json
  Icons/Sources/Icons/Icons.xcassets/tag.fill.imageset/Contents.json
  Icons/Sources/Icons/Icons.xcassets/tray.fill.imageset/Contents.json
  Icons/Sources/Icons/Icons.xcassets/xmark.imageset/Contents.json
  Icons/Sources/Icons/Icons.xcassets/xmark.rounded.bold.imageset/Contents.json
  Icons/Templates/icons.stencil
  Palette/Sources/Palette/Palette.swift
  Palette/Templates/palette.stencil
  Shared/ContentView.swift
  Shared/Persistence.swift
  Shared/StackOvApp.swift
  StackOv.xcodeproj/project.pbxproj
Labels: Service task, hotfix

#52 PostView background filling was fixed
  Flows/HomeFlow/Sources/HomeFlow/PostView/PostView.swift
Labels: bug

#50 Feature/27 add simple infinity scrolling
  Components/Sources/Components/LoaderView/LoaderCircle.swift
  Components/Sources/Components/LoaderView/LoaderView.swift
  Flows/HomeFlow/Sources/HomeFlow/PageView/PageView.swift
  Palette/Sources/Palette/Palette.swift
  Palette/Sources/Palette/Palette.xcassets/PaleSky.colorset/Contents.json
  Stores/PageStore/Sources/PageStore/Models/QuestionModel.swift
  Stores/PageStore/Sources/PageStore/PageDataManager/PageDataManager.swift
  Stores/PageStore/Sources/PageStore/PageDataManager/PageDataManagerProtocol.swift
  Stores/PageStore/Sources/PageStore/PageStore.swift
Labels: feature

#59 White theme first try
  Components/Sources/Components/FilterButton.swift
  Components/Sources/Components/TagButton.swift
  Flows/HomeFlow/Sources/HomeFlow/FilterView/FilterView.swift
  Flows/HomeFlow/Sources/HomeFlow/FilterView/Rows/FilterOptionRow.swift
  Flows/HomeFlow/Sources/HomeFlow/FilterView/Rows/SortOptionRow.swift
  Flows/HomeFlow/Sources/HomeFlow/HomeFlow.swift
  Flows/HomeFlow/Sources/HomeFlow/PageView/PageView.swift
  Flows/HomeFlow/Sources/HomeFlow/PostItemView/PostItemInfoView.swift
  Flows/HomeFlow/Sources/HomeFlow/PostItemView/PostItemView.swift
  Flows/HomeFlow/Sources/HomeFlow/PostView/PostView.swift
  Flows/MainFlow/Sources/MainFlow/PadContentView.swift
  Flows/MainFlow/Sources/MainFlow/PhoneContentView.swift
  Flows/MainFlow/Sources/MainFlow/Sidebar/SidebarButton.swift
  Flows/MainFlow/Sources/MainFlow/Sidebar/SidebarView.swift
  Icons/Sources/Icons/Icons.xcassets/eye.fill.imageset/eye.fill.svg
  Palette/Sources/Palette/Palette.swift
  Palette/Sources/Palette/Palette.xcassets/Bluishwhite.colorset/Contents.json
  Palette/Sources/Palette/Palette.xcassets/DarkDivider.colorset/Contents.json
  Palette/Sources/Palette/Palette.xcassets/DarkGray.colorset/Contents.json
  Palette/Sources/Palette/Palette.xcassets/LightBlack.colorset/Contents.json
  Palette/Sources/Palette/Palette.xcassets/LightDeepGray.colorset/Contents.json
  Palette/Sources/Palette/Palette.xcassets/LightDivider.colorset/Contents.json
  Palette/Sources/Palette/Palette.xcassets/LightGray.colorset/Contents.json
  Palette/Sources/Palette/Palette.xcassets/PeriwinkleCrayola.colorset/Contents.json
  Palette/Sources/Palette/Palette.xcassets/SlateGray.colorset/Contents.json
  Palette/Sources/Palette/Palette.xcassets/SlateGrayLight.colorset/Contents.json
Labels: Any device, Layout

#67 Signin was changed to manual
  StackOv.xcodeproj/project.pbxproj
Labels: Service task

#69 Feature/37 mainflow accessibility refactoring
  Components/Sources/Components/FilterButton.swift
  Flows/HomeFlow/Sources/HomeFlow/PageView/PageView.swift
  Flows/MainFlow/Sources/MainFlow/PadContentView.swift
  Flows/MainFlow/Sources/MainFlow/Sidebar/SidebarButton.swift
Labels: feature

#64 Implementing Loading and Error states for PageView
  Components/Sources/Components/ShimmerView/ShimmerConfig.swift
  Components/Sources/Components/ShimmerView/ShimmerModifier.swift
  Components/Sources/Components/ShimmerView/ShimmerView.swift
  Components/Sources/Components/ShimmerView/View+Extension.swift
  Flows/HomeFlow/Sources/HomeFlow/PageView/PageView.swift
  Flows/HomeFlow/Sources/HomeFlow/PostItemLoadingView/PostItemLoadingView.swift
  StackOv.xcodeproj/project.pbxproj
  Stores/PageStore/Sources/PageStore/PageStore.swift
Labels: Any device, feature
